[project]
name = "pexp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = 'DESKTOP-K3TJ618\user', email = "starryarea@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
]

[project.scripts]
pexp = "pexp:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
